### PR TITLE
change method of finding dataset

### PR DESCRIPTION
**Pull request by DaisyVinter**
Method of finding project ID changed to make simpler and use environment variable.
Method of finding dataset record ID changed to make robust to change in dataset location or name.

### CODE REVIEW

**Review by ctdarwell — COMMENTED** [review]
A105 - the variable `project_id` is not declared

A106 - "non-cancer illness code" field is NA and causes NB to fail. Also, failed at line `tbl %>% filter(...` 

All else is good

**Comment by DaisyVinter** [comment]
A106 - "non-cancer illness code" field is NA and causes NB to fail. Also, failed at line tbl %>% filter(... 
fails because of the change in data structure from collapsed list to arrayed. Added a note about versions, will be addressed in another branch.

**Review by ctdarwell — COMMENTED** [review]
Looks good

**Review by ctdarwell — COMMENTED** [review]
OK

**Review by ctdarwell — APPROVED** [review]
OK

**Pull request merged**
